### PR TITLE
Create merge_sort_python.py

### PR DESCRIPTION
**Pull request by malikrohit16**

### CODE REVIEW

**Review by khanchi97 — CHANGES_REQUESTED** [review]
Hello @malikrohit16  well its great !! 
now the only thing which is left is name of the file means it should be a .py file.

**Comment by malikrohit16** [comment]
check it now

**Review by khanchi97 — CHANGES_REQUESTED** [review]
Hello @malikrohit16 your task was that you had to change file name `merge_sort_python` to `merge_sort_python.py` .
Not your commit title.

**Review by malikrohit16 — COMMENTED** [review]
check it now

**Review by khanchi97 — APPROVED** [review]
great :tada:

**Comment by khanchi97** [comment]
It would be great if you could document it well.

**Pull request merged**
