### PR TITLE
Created exponential_search.c

### PR DESCRIPTION
**Pull request by sidntrivedi**

### CODE REVIEW

**Review by 22shubh22 — CHANGES_REQUESTED** [review]
Sort array before searching.

**Comment by sidntrivedi** [comment]
Ok Sir. Will it not increase the time complexity of algorithm?

**Comment by 22shubh22** [comment]
It will. But this search cannot take place without a sorted array.

**Comment by sidntrivedi** [comment]
Okay Sir.Making changes.

**Comment by sidntrivedi** [comment]
I am closing this PR and will make a new PR with the asked changes.

**Pull request closed without merging**
