### PR TITLE
Greedy Algorithms

### PR DESCRIPTION
**Pull request by abhisheknalla**
I have added the following greedy algorithms:
1. activitySelection.cpp 
2. jobSequencing.cpp
3. Prim.cpp
4. huffmanCoding.py
5. Kruskal.cpp
6. travellingSalesman.c

Can you review the codes and merge them ?

### CODE REVIEW

**Comment by abhisheknalla** [comment]
I added README files describing the problems and the solutions for each of the algorithms.

**Review by khanchi97 — CHANGES_REQUESTED** [review]
when running these programs, they didn't even prompt about what I have to enter.Please make some required changes.And from now please make different PR for different implementations.Should not be in one PR.

**Comment by abhisheknalla** [comment]
Added input prompts and example test cases in readme files

**Comment by khanchi97** [comment]
Great work @abhisheknalla  🎉

**Review by khanchi97 — APPROVED** [review]

**Comment by khanchi97** [comment]
@abhisheknalla currently merging now but next time don't make a PR with multiple no. of commits.There should be only one implementation with one PR.

**Comment by khanchi97** [comment]
And after this will be merged you can try to make these implementations easier for viewers.In another PR.

**Pull request merged**
