### PR TITLE
Topological Sort - lang cpp added #40

### PR DESCRIPTION
**Pull request by kiryteo**
filename: topological_sort.cpp

### CODE REVIEW

**Review by khanchi97 — CHANGES_REQUESTED** [review]
Also, add a README file for this, describing about what it does and how this is implemented.

**Comment by kiryteo** [comment]
As such, there is no separate readme file for other algos, should I make the code more documented.?

**Comment by khanchi97** [comment]
I know readme file is not present for those algos who had been merged before, but now it has to be.

**Comment by kiryteo** [comment]
Added readme_topological.txt explaining the algorithm used for topological sort.

**Review by 22shubh22 — CHANGES_REQUESTED** [review]
@kiryteo your topological_sort doesn't work for following test case.
5
0 1 0 1 0
0 0 1 0 1
0 0 0 0 0
0 1 0 0 1
0 0 1 0 0

Output should be 1 4 2 5 3.
Problem may lie between line 53 - 59.

**Comment by kiryteo** [comment]
I see, the implementation doesn't handle some test cases.. I'll try a different approach and add the file

**Comment by 22shubh22** [comment]
ok.

**Pull request closed without merging**
