### PR TITLE
Created Exponential_search.c

### PR DESCRIPTION
**Pull request by sidntrivedi**
Sir,kindly review.

### CODE REVIEW

**Review by 22shubh22 — CHANGES_REQUESTED** [review]
Searching doesn't give original index of numbers (which was before sorting) and thus gives incorrect index positions.

**Comment by sidntrivedi** [comment]
Sir,so should we give a message to the user to enter sorted array?

**Comment by 22shubh22** [comment]
No. apply mapping technique OR create another array storing array index and sort it with the original array.

**Comment by sidntrivedi** [comment]
Ok Sir.

**Comment by sidntrivedi** [comment]
Sir,but we need the user to give a sorted array since it is made to work on sorted arrays only as is the case with binary search.

**Comment by 22shubh22** [comment]
Okay fine, this repo holds only the concepts and tricks.
I was insisting you because this may not be the case in programming contest/problem.
 Thanks for exponential search.

**Review by 22shubh22 — APPROVED** [review]

**Comment by sidntrivedi** [comment]
Ok Sir. Thanks for your approval. Please guide about the final report.

**Pull request merged**
