### PR TITLE
Added binary search in c

### PR DESCRIPTION
**Pull request by gurjot273**
Added binary search in c. The index of element found is with respect to sorted array not unsorted

Used the insertionsort function for producing the sorted array which is searched by the binary search function.

### CODE REVIEW

**Review by 22shubh22 — CHANGES_REQUESTED** [review]
If an element is found in array, the index is not providing with the exact location but with sorted location. Update your code so that the exact/original index is returned.

**Comment by gurjot273** [comment]
I have made the required modification in the code along with comments supporting it and is now returning the original index. Please review it once again @22shubh22

**Review by 22shubh22 — APPROVED** [review]

**Comment by 22shubh22** [comment]
Since this code will not answer if duplicates are involved in the array (two or more same values in an array). I am creating a new issue to deal with answering every occurrence of a key in binary search.
@gurjot273 you better deal with that. This commit of your's will be merged.

**Review by khanchi97 — APPROVED** [review]
Great 🎉

**Pull request merged**
