### PR TITLE
0-1 knapsack problem in c++

### PR DESCRIPTION
**Pull request by minchi19**
Created a folder name greedy algo and added 0-1 knapsack in it.

### CODE REVIEW

**Review by 22shubh22 — CHANGES_REQUESTED** [review]
Include question statement and also document it

**Review by 22shubh22 — CHANGES_REQUESTED** [review]
Include problem statement and also document code.

**Comment by minchi19** [comment]
By document code you mean to say text file on how this code works??

**Comment by 22shubh22** [comment]
yes

**Comment by minchi19** [comment]
Done please review it

**Review by 22shubh22 — APPROVED** [review]
Making a 2D array consumes a lot of space. Think for a better solution. Also please improve your Read-me file to make newcomers/beginner to understand this problem with your code.

**Pull request merged**
